config/routes.rb
CourseReviews::Application.routes.draw do
  resources :courses do
    resources :reviews
  end
  devise_for :users
  
  match "search" => "home#search"

  root :to => 'home#index'

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :reviews
  attr_accessible :code, :description, :title
  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :course
  attr_accessible :comment, :homework_time, :public, :reviewer_year, :semester, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_filter :authenticate_user!
  protect_from_forgery
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])
    @reviews = @course.reviews.where(:public => true)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @course }
    end
  end

  # GET /courses/new
  # GET /courses/new.json
  def new
    @course = Course.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.json
  def create

    @course = Course.new(params[:course])

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, :notice => 'Course was successfully created.' }
        format.json { render :json => @course, :status => :created, :location => @course }
      else
        format.html { render :action => "new" }
        format.json { render :json => @course.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    if not current_user.try(:professor?)
      head :no_content
      return
    end
    @course = Course.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to @course, :notice => 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @course.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    if not current_user.try(:professor?)
      head :no_content
      return
    end
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def search
    query = "%#{params[:query]}%"
    @courses = Course.where("code LIKE :q or title LIKE :q or description LIKE :q", :q => query)
    @reviews = Review.where("comment LIKE :q", :q => query)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @course = Course.find(params[:course_id])
    @review = @course.reviews.create(params[:review])
    redirect_to course_path(@course)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<%= content_for :toolbar_right do %>
<p class="navbar-text pull-right">
  <%= link_to 'Back', "/", :class => "navbar-link", :style => "text-decoration:none;margin-left:20px" %>
</p>
<% end %>

<h1>Courses</h1>

<table class ="table table-condensed table-striped">
  <tr>
    <th>Code</th>
    <th>Title</th>
  </tr>

<% @courses.each do |course| %>
  <tr>
    <td><%= course.code %></td>
    <td><%= link_to course.title, course %></td>
    <!-- <td><%= link_to 'Edit', edit_course_path(course) %></td> -->
    <!-- <td><%= link_to 'Destroy', course, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td> -->
  </tr>
<% end %>
</table>

<br />

<% if current_user.try(:professor?) %><%= link_to 'New Course', new_course_path %><% end %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<%= content_for :toolbar_left do %>
<a class="brand" href="#"><%= @course.code %></a>
<% end %>
<%= content_for :toolbar_right do %>
<p class="navbar-text pull-right">
  <%= link_to 'Back', courses_path, :class => "navbar-link", :style => "text-decoration:none;margin-left:20px" %>
</p>
<ul class="nav">
  <li><a href="#">Review</a></li>
  <% if current_user.try(:professor?) %><li><%= link_to 'Edit', edit_course_path(@course) %></li><% end %>
</ul>
<% end %>


<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
            <a href="/"><img src ="/Logo.png" /></a>

    </div>

    <div class="span10">
        <!--Body content-->


        <% if notice %><p id="notice"><%= notice %></p><% end %>

        <dl class="dl-horizontal">
          <dt class="course_title">Title:</dt>
          <dd><%= @course.title %></dd>


          <dt class="course_code">Code:</dt>
          <dd><%= @course.code %></dd>


          <dt class="course_description">Description:</dt>
          <dd><%= @course.description %>&nbsp;</dd>
		  
		  <% unless @reviews.empty? %>
		  <% times = @reviews.map(&:homework_time).compact %>
		  <dt>Average homework:</dt>
		  <dd><%= pluralize(times.sum / times.length, "hour") %> per week</dd>
		  <% end %>
        </dl>
		
		
		<% if @reviews.empty? %>
		This course has no reviews.
		<% else %>
		<h3><%= pluralize(@reviews.count, "Reviews") %></h3>
		<table class="table table-striped">
		<% for review in @reviews %>
		<tr>
			<td width="200"><small>
				Homework per week: <%= pluralize(review.homework_time, "hour") %><br>
				Taken in <%= review.semester %><br>
				Class of <%= review.reviewer_year %><br>
			</small></td>
			<td style="font-size:120%">&ldquo;<%=h review.comment %>&rdquo;</td>
		</tr>
		<% end %>
		</table>
		<% end %>
        
        <h4><a data-toggle="collapse" href="#theform" class="btn">Review this Course</a></h4>
        <%= form_for([@course, @course.reviews.build], :html => { :id => "theform", :class => "collapse" }) do |f| %>
        <div class="field">
          <%= f.text_field :semester, :placeholder => "Semester taken", :class => "span4" %>
        </div>
        <div class="field">
		  <%= f.label :user_id do%>Professor: <%= f.collection_select(:user_id, User.where(:professor => true), :id, :email) %><% end %>
        </div>
        <div class="field">
          <%= f.number_field :reviewer_year, :placeholder => "Your class year", :class => "span4" %>
        </div>
        <div class="field">
          <%= f.label :public, :class => "checkbox" do %><%= f.check_box :public %> Allow my review to be publicly visible<% end %>
        </div>
        <div class="field">
          <%= f.number_field :homework_time, :placeholder => "Hours spent on homework per week", :class => "span4" %>
        </div>
        <div class="field">
          <%= f.text_area :comment, :cols => 40, :rows => 5, :placeholder => "Comments (optional)", :class => "span4" %>
        </div>
        <div class="actions">
          <%= f.submit "Post Review", :class => "btn btn-primary" %>
        </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%= content_for :toolbar_left do %>
<div class="brand" style="padding:5px"><img src ="schools.png" width="200" style="float:left"></div>
<% end %>

<img src ="Logo.png" width="500" height="500" > 

<%= form_tag "/search", :class => "form-search" do %>
<div class="input-append">
	<%= search_field_tag "query", nil, :autofocus => true, :placeholder => "HSA 010 Underwater Basketweaving", :class => "search-query" %>
	<%= button_tag "Search", :class => "btn" %>
</div>
<% end %>
<!-- <img src ="Searchfor.png" width="100" height="100" > -->
<!-- <br> -->
<%= link_to "All Courses", courses_path %>

app/views/home/search.html.erb
<%= content_for :toolbar_right do %>
<p class="navbar-text pull-right">
  <%= link_to 'Back', courses_path, :class => "navbar-link", :style => "text-decoration:none;margin-left:20px" %>
</p>
<% end %>

<h1>Search Results</h1>

<% results = {"course" => @courses.length, "review" => @reviews.length}.reject {|k,v| v.zero? } %>
<% if results.empty? %>
<p>No results found! <%= link_to 'Back', :back %></p>
<% else %>
<p><%= results.map {|k,v| pluralize(v, k) }.join " and " %> found.</p>
<% end %>

<% unless @courses.empty? %>
	<h2>Courses</h2>
	<table class ="table table-condensed table-striped">
	  <tr>
	    <th>Code</th>
	    <th>Title</th>
	  </tr>
	<% @courses.each do |course| %>
	  <tr>
	    <td><%= course.code %></td>
	    <td><%= link_to course.title, course %></td>
	  </tr>
	<% end %>
	</table>
<% end %>

<% unless @reviews.empty? %>
	<h2>Reviews</h2>
	<table class ="table table-condensed table-striped">
	  <tr>
	    <th>Course</th>
	    <th>Comment</th>
	  </tr>
	<% @reviews.each do |review| %>
	  <tr>
	    <td><%= review.course.code %></td>
	    <td><%= review.comment %></td>
	  </tr>
	<% end %>
	</table>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>5C Course Reviews</title>
  <% if notice %><div class="alert alert-info"><%= notice %><button type="button" class="close" data-dismiss="alert">&times;</button></div><% end %>
  <% if alert %><div class="alert alert-error"><%= alert %><button type="button" class="close" data-dismiss="alert">&times;</button></div><% end %>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= stylesheet_link_tag params[:controller] %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
      </button>
	  <%= yield :toolbar_left %>
	  <!-- Login form -->
      <div class="nav-collapse collapse">
	  <%= yield :toolbar_right %>
	  <% if user_signed_in? %>
	    <p class="navbar-text pull-right"><%= current_user.email %> (<%= link_to "sign out", destroy_user_session_path, :method => :delete %>)</p>
	  <% else %>
	    <%= form_for("user", :url => user_session_path, :html => {:class => "navbar-form pull-right"}) do |f| %>
	      <%= f.text_field :email, :placeholder => "Email", :class => "span2" %>
	      <%= f.password_field :password, :placeholder => "Password", :class => "span2" %>
	      <%= f.submit 'Sign in', :class => "btn" %>
	    <% end %>
	  <% end %>
	  </div>
    </div>
  </div>
</div>

<%= yield %>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>5C Course Reviews: Authentication</title>
  <% if notice %><div class="alert alert-info"><%= notice %><button type="button" class="close" data-dismiss="alert">&times;</button></div><% end %>
  <% if alert %><div class="alert alert-error"><%= alert %><button type="button" class="close" data-dismiss="alert">&times;</button></div><% end %>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= stylesheet_link_tag params[:controller] %>
  <style>
	  body {
		  background-color: #f5f5f5;
		  max-width: 360px;
		  margin: 0px auto;
	  }
  </style>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<p><a href="/">Home</a></p>
<%= yield %>

</body>
</html>